import { useEffect, useState } from "react";
import { useAuth } from "../contexts/AuthContext";
import { useGamification } from "../contexts/GamificationContext";
import { generateMealPlan } from "../lib/gemini";
import { saveMealPlan, getMealPlan } from "../lib/firestore";
import type { DailyMealPlan, Meal } from "../lib/types";
import { PieChart, Pie, Cell, ResponsiveContainer } from "recharts";

const CUISINES = ["Indian", "Chinese", "Italian", "Mediterranean", "Japanese", "Mexican", "Thai", "Korean"];
const COOK_TIMES = [
    { value: "quick", label: "Under 20 min" },
    { value: "medium", label: "20–45 min" },
    { value: "elaborate", label: "45+ min" },
];
const SPICE = ["Mild", "Medium", "Spicy"];
const MEALS = ["breakfast", "lunch", "dinner", "snack"] as const;
const MACRO_COLORS = ["#22c55e", "#3b82f6", "#f59e0b"]; // protein, carbs, fats

export default function MealsPage() {
    const { user, profile } = useAuth();
    const { checkAndUnlock } = useGamification();
    const [dayOffset, setDayOffset] = useState(0);
    const [meals, setMeals] = useState<DailyMealPlan | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");
    const [cuisine, setCuisine] = useState("Indian");
    const [cookTime, setCookTime] = useState("medium");
    const [spice, setSpice] = useState("Medium");
    const [expanded, setExpanded] = useState<string | null>(null);
    const [showRecipe, setShowRecipe] = useState<string | null>(null);
    const [dishImages, setDishImages] = useState<Record<string, string>>({});
    const [shareMsg, setShareMsg] = useState("");

    function getDateStr(offset: number) {
        const d = new Date(); d.setDate(d.getDate() + offset); return d.toISOString().split("T")[0];
    }

    function getDayLabel(offset: number) {
        if (offset === 0) return "Today";
        if (offset === 1) return "Tomorrow";
        const d = new Date(); d.setDate(d.getDate() + offset);
        return d.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
    }

    useEffect(() => {
        async function load() {
            if (!user) return;
            const saved = await getMealPlan(user.uid, getDateStr(dayOffset));
            setMeals(saved);
            if (saved) loadImages(saved);
        }
        load();
    }, [user, dayOffset]);

    async function loadImages(plan: DailyMealPlan) {
        const images: Record<string, string> = {};
        for (const type of MEALS) {
            const m = (plan as any)[type] as Meal | undefined;
            if (m?.imageQuery || m?.name) {
                const query = m.imageQuery || m.name;
                // Use Unsplash source (no API key needed) for free images
                images[type] = `https://source.unsplash.com/400x300/?${encodeURIComponent(query + " food dish")}`;
            }
        }
        setDishImages(images);
    }

    async function generate() {
        if (!user || !profile) return;
        setLoading(true); setError("");
        try {
            const ctx = `Name:${profile.name}, Age:${profile.age}, Gender:${profile.gender}, Weight:${profile.weight}kg, Height:${profile.height}cm, BMI:${profile.bmi}, Goal:${profile.goal}, Activity:${profile.activityLevel}, Diet:${profile.dietType}, Allergies:${(profile.allergies || []).join(",") || "None"}, Food Dislikes:${(profile.foodDislikes || []).join(",") || "None"}, Preferred Cuisines:${(profile.cuisinePreference || []).join(",") || cuisine}, Medical:${(profile.medicalConditions || []).join(",") || "None"}, Budget:₹${profile.weeklyBudget}/week, Location:${profile.location}, Selected Cuisine:${cuisine}, Cook Time:${cookTime}, Spice Level:${spice}`;
            const raw = await generateMealPlan(ctx);
            const cleaned = raw.replace(/```json\n?|```\n?/g, "").trim();
            const parsed = JSON.parse(cleaned);
            await saveMealPlan(user.uid, getDateStr(dayOffset), parsed);
            setMeals(parsed);
            loadImages(parsed);
            checkAndUnlock("10_plans"); // Check meal planner pro achievement
        } catch (e: any) { setError(e.message || "Could not generate meals."); }
        setLoading(false);
    }

    async function sharePlan() {
        if (!meals) return;
        const text = MEALS.map(type => {
            const m = (meals as any)[type] as Meal | undefined;
            if (!m) return "";
            return `🍽 ${type.toUpperCase()}: ${m.name} (${m.calories} kcal)\n   Recipe: ${(m.recipe || []).join(" → ")}`;
        }).filter(Boolean).join("\n\n");

        const shareText = `🌿 CHIKITSA Meal Plan for ${getDayLabel(dayOffset)}\n\n${text}\n\nGenerated by CHIKITSA — AI Nutrition App`;

        try {
            if (navigator.share) {
                await navigator.share({ title: "CHIKITSA Meal Plan", text: shareText });
            } else {
                await navigator.clipboard.writeText(shareText);
                setShareMsg("Copied to clipboard! 📋");
                setTimeout(() => setShareMsg(""), 3000);
            }
            checkAndUnlock("first_share");
        } catch { /* cancelled */ }
    }

    function MacroChart({ meal }: { meal: Meal }) {
        const data = [
            { name: "Protein", value: meal.protein, color: MACRO_COLORS[0] },
            { name: "Carbs", value: meal.carbs, color: MACRO_COLORS[1] },
            { name: "Fats", value: meal.fats, color: MACRO_COLORS[2] },
        ];
        return (
            <div className="flex items-center gap-3">
                <div className="w-16 h-16">
                    <ResponsiveContainer width="100%" height="100%">
                        <PieChart>
                            <Pie data={data} dataKey="value" cx="50%" cy="50%" innerRadius={18} outerRadius={28} paddingAngle={3} strokeWidth={0}>
                                {data.map((d, i) => <Cell key={i} fill={d.color} />)}
                            </Pie>
                        </PieChart>
                    </ResponsiveContainer>
                </div>
                <div className="flex flex-col gap-0.5">
                    {data.map(d => (
                        <div key={d.name} className="flex items-center gap-1.5">
                            <div className="w-2 h-2 rounded-full" style={{ background: d.color }} />
                            <span className="text-[10px] text-slate-500 dark:text-slate-400">{d.name}: {d.value}g</span>
                        </div>
                    ))}
                </div>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">Meal Plan</h1>
                {meals && (
                    <button onClick={sharePlan} className="px-4 py-2 rounded-lg text-xs font-semibold bg-blue-50 dark:bg-blue-950 text-blue-600 dark:text-blue-400 border border-blue-200 dark:border-blue-800 hover:bg-blue-100 dark:hover:bg-blue-900 transition-colors">
                        📤 Share Plan
                    </button>
                )}
            </div>

            {shareMsg && <div className="bg-green-50 dark:bg-green-950/30 border border-green-200 dark:border-green-800 rounded-xl px-4 py-2.5 text-xs font-medium text-green-600 dark:text-green-400">{shareMsg}</div>}

            {/* Day tabs */}
            <div className="flex gap-2 overflow-x-auto pb-1 -mx-1 px-1">
                {[0, 1, 2, 3, 4, 5, 6].map((i) => (
                    <button key={i} onClick={() => setDayOffset(i)}
                        className={`px-4 py-2 rounded-lg text-xs font-semibold whitespace-nowrap shrink-0 transition-colors border
                        ${dayOffset === i ? "bg-green-600 text-white border-green-600" : "bg-white dark:bg-slate-900 text-slate-600 dark:text-slate-400 border-slate-100 dark:border-slate-800 hover:border-slate-200 dark:hover:border-slate-700"}`}>
                        {getDayLabel(i)}
                    </button>
                ))}
            </div>

            {/* Preference panel */}
            <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-100 dark:border-slate-800 p-4 sm:p-5">
                <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 mb-3">Preferences</h2>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div>
                        <label className="block text-[11px] font-semibold text-slate-500 dark:text-slate-400 mb-1.5 uppercase tracking-wider">Cuisine</label>
                        <select value={cuisine} onChange={(e) => setCuisine(e.target.value)}
                            className="w-full px-3 py-2.5 rounded-lg text-sm bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-slate-200 outline-none focus:border-green-500">
                            {CUISINES.map((c) => <option key={c} value={c}>{c}</option>)}
                        </select>
                    </div>
                    <div>
                        <label className="block text-[11px] font-semibold text-slate-500 dark:text-slate-400 mb-1.5 uppercase tracking-wider">Cook Time</label>
                        <select value={cookTime} onChange={(e) => setCookTime(e.target.value)}
                            className="w-full px-3 py-2.5 rounded-lg text-sm bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-slate-200 outline-none focus:border-green-500">
                            {COOK_TIMES.map((c) => <option key={c.value} value={c.value}>{c.label}</option>)}
                        </select>
                    </div>
                    <div>
                        <label className="block text-[11px] font-semibold text-slate-500 dark:text-slate-400 mb-1.5 uppercase tracking-wider">Spice Level</label>
                        <div className="flex gap-2">
                            {SPICE.map((s) => (
                                <button key={s} onClick={() => setSpice(s)}
                                    className={`flex-1 py-2.5 rounded-lg text-xs font-semibold transition-colors border
                                    ${spice === s ? "bg-green-50 dark:bg-green-950 text-green-700 dark:text-green-400 border-green-200 dark:border-green-800" : "bg-slate-50 dark:bg-slate-800 text-slate-500 dark:text-slate-400 border-slate-200 dark:border-slate-700"}`}>
                                    {s}
                                </button>
                            ))}
                        </div>
                    </div>
                </div>
                <button onClick={generate} disabled={loading}
                    className="mt-4 w-full sm:w-auto px-6 py-2.5 rounded-lg text-sm font-semibold bg-green-600 text-white hover:bg-green-700 transition-colors disabled:opacity-50">
                    {loading ? "Generating..." : "Generate Plan"}
                </button>
            </div>

            {error && <div className="bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 rounded-xl px-4 py-3 text-sm text-red-600 dark:text-red-400">{error}</div>}

            {/* Meal cards with recipes and images */}
            {meals && (
                <div className="grid grid-cols-1 gap-4">
                    {MEALS.map((type) => {
                        const m = (meals as any)[type] as Meal | undefined;
                        if (!m) return null;
                        const isExpanded = expanded === type;
                        const isRecipeOpen = showRecipe === type;
                        const img = dishImages[type];

                        return (
                            <div key={type} className="bg-white dark:bg-slate-900 rounded-xl border border-slate-100 dark:border-slate-800 overflow-hidden">
                                {/* Image banner */}
                                {img && (
                                    <div className="h-40 sm:h-48 overflow-hidden relative">
                                        <img src={img} alt={m.name} className="w-full h-full object-cover" loading="lazy"
                                            onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }} />
                                        <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
                                        <div className="absolute bottom-3 left-4 right-4">
                                            <span className="text-[10px] font-bold uppercase tracking-widest text-green-400">{type}</span>
                                            <h3 className="text-lg font-bold text-white">{m.name}</h3>
                                        </div>
                                        <div className="absolute top-3 right-3 bg-black/50 backdrop-blur-sm text-white text-xs font-bold px-3 py-1 rounded-full">
                                            {m.calories} kcal
                                        </div>
                                    </div>
                                )}

                                {/* Content */}
                                <div className="p-4 sm:p-5">
                                    {!img && (
                                        <div className="flex items-center justify-between mb-3">
                                            <div>
                                                <span className="text-[10px] font-bold uppercase tracking-widest text-green-600 dark:text-green-400">{type}</span>
                                                <h3 className="text-base font-bold text-slate-900 dark:text-white">{m.name}</h3>
                                            </div>
                                            <span className="text-sm font-bold text-slate-500 dark:text-slate-400">{m.calories} kcal</span>
                                        </div>
                                    )}

                                    {/* Timing */}
                                    {(m.prepTime || m.cookTime) && (
                                        <div className="flex gap-4 mb-3 text-xs text-slate-500 dark:text-slate-400">
                                            {m.prepTime && <span>⏱ Prep: {m.prepTime}</span>}
                                            {m.cookTime && <span>🍳 Cook: {m.cookTime}</span>}
                                        </div>
                                    )}

                                    {/* Macro chart */}
                                    <MacroChart meal={m} />

                                    {/* Action buttons */}
                                    <div className="flex gap-2 mt-4">
                                        {m.ingredients && (
                                            <button onClick={() => setExpanded(isExpanded ? null : type)}
                                                className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-50 dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600 transition-colors">
                                                {isExpanded ? "Hide ingredients" : "📋 Ingredients"}
                                            </button>
                                        )}
                                        {m.recipe && m.recipe.length > 0 && (
                                            <button onClick={() => setShowRecipe(isRecipeOpen ? null : type)}
                                                className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-green-50 dark:bg-green-950 text-green-600 dark:text-green-400 border border-green-200 dark:border-green-800 hover:bg-green-100 dark:hover:bg-green-900 transition-colors">
                                                {isRecipeOpen ? "Hide recipe" : "👨‍🍳 View Recipe"}
                                            </button>
                                        )}
                                    </div>

                                    {/* Ingredients */}
                                    {isExpanded && m.ingredients && (
                                        <div className="mt-3 pt-3 border-t border-slate-100 dark:border-slate-800">
                                            <div className="flex flex-wrap gap-1.5">
                                                {(Array.isArray(m.ingredients) ? m.ingredients : []).map((ing: any, i: number) => (
                                                    <span key={i} className="text-[11px] bg-slate-50 dark:bg-slate-800 text-slate-600 dark:text-slate-400 px-2.5 py-1 rounded-lg border border-slate-100 dark:border-slate-700">
                                                        {typeof ing === "string" ? ing : `${ing.item} (${ing.quantity})`}
                                                    </span>
                                                ))}
                                            </div>
                                            {m.explanation && <p className="text-xs text-slate-500 dark:text-slate-400 mt-2 leading-relaxed italic">{m.explanation}</p>}
                                        </div>
                                    )}

                                    {/* Recipe steps */}
                                    {isRecipeOpen && m.recipe && (
                                        <div className="mt-3 pt-3 border-t border-slate-100 dark:border-slate-800">
                                            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 mb-2">Recipe Steps</h4>
                                            <ol className="space-y-2">
                                                {m.recipe.map((step, i) => (
                                                    <li key={i} className="flex items-start gap-3">
                                                        <span className="w-5 h-5 rounded-full bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-400 text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5">
                                                            {i + 1}
                                                        </span>
                                                        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{step.replace(/^Step \d+:\s*/i, "")}</p>
                                                    </li>
                                                ))}
                                            </ol>
                                        </div>
                                    )}
                                </div>
                            </div>
                        );
                    })}
                </div>
            )}

            {!meals && !loading && (
                <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-100 dark:border-slate-800 p-8 text-center">
                    <p className="text-sm text-slate-500 dark:text-slate-400">No plan for {getDayLabel(dayOffset)}. Set your preferences above and click Generate.</p>
                </div>
            )}

            {loading && (
                <div className="flex flex-col items-center justify-center py-12 gap-3">
                    <div className="w-8 h-8 rounded-full border-2 border-slate-200 dark:border-slate-700 border-t-green-600 animate-spin" />
                    <p className="text-xs text-slate-400 dark:text-slate-500">Crafting your personalized meal plan with recipes...</p>
                </div>
            )}
        </div>
    );
}
